### ISSUE TITLE
1.6版本中，inquisitor中很多分析器（Analyzers）不可用

### ISSUE THREAD

**Issue by Caimany** [hangxin1940/elasticsearch-cn-out-of-box#1]
org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer [pct_spliter]
.... ....
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
报了很多类似的错误，包括ik，mmseg等分析器

**Comment by hangxin1940** [comment]
inquisitor里如果没有选择index什么的话,一些分析器是不起作用的.
可以尝试创建个index,并在这个index下再进行测试.
另外,有些是分词器,有些是分析器,混用也会出错.

**Comment by Caimany** [comment]
我看了一些插件主页，都是支持1.4或者1.5的，可以兼容1.6吗？

**Comment by hangxin1940** [comment]
能用,兼容,我才放上去的.

**Comment by YJingLee** [comment]
什么时候有空升级到1.7.1版本

**Comment by hangxin1940** [comment]
有时间了我就升上去
