### ISSUE TITLE
配置文件问题：默认构建拒绝外部REST请求，只接受本机HTTP请求

### ISSUE THREAD

**Issue by yue9944882** [hangxin1940/elasticsearch-cn-out-of-box#2]
# 多机分布式直接运行本项目存在这个问题：

所有Nodes只能接受本机的Rest请求，如

curl ‘http://localhost:9200/_cat/health?v’ 

可以正常得到结果，然而

curl 'http://xx.xx.xx.xx:9200/_cat/health?v' 

HTTP连接请求会被拒绝
# 解决办法：

在$ES_HOME/config/elasticsearch.yml文件中添加两行：
network.host: 0.0.0.0
http.host: 0.0.0.0
即可允许外部HTTP请求申请Rest资源

参考链接：[http://stackoverflow.com/questions/15503455/elasticsearch-allow-only-local-requests](http://stackoverflow.com/questions/15503455/elasticsearch-allow-only-local-requests)

**Comment by hangxin1940** [comment]
thanks
